[[plugins]]
repo = 'Shougo/dein.vim'

# ==================================================
# colors
# ==================================================

[[plugins]]
repo = 'cocopon/iceberg.vim'

# ==================================================
# basic
# ==================================================

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
hook_add = '''
source ~/.config/nvim/plugins/vimfiler.rc.vim
'''

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# ==================================================
# snippet
# ==================================================
[[plugins]]
repo = 'SirVer/ultisnips'

# ==================================================
# powerline
# ==================================================

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
source ~/.config/nvim/plugins/airline.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
hook_add = '''
let g:airline_theme='luna'
'''

